CLASSES = {
    "Activity": [
        "std::string 	Name () const",
        "void 	SetName (std::string Name)",
        "discordpp::ActivityTypes 	Type () const",
        "void 	SetType (discordpp::ActivityTypes Type)",
    ],
    # "ActivityAssets": [],
    # "ActivityInvite": [],
    # "ActivityParty": [],
    # "ActivitySecrets": [],
    # "ActivityTimestamps": [],
    # "AdditionalContent": [],
    # "AudioDevice": [],
    # "AuthorizationArgs": [],
    # "AuthorizationCodeChallenge": [],
    # "AuthorizationCodeVerifier": [],
    # "Call": [],
    # "CallInfoHandle": [],
    # "ChannelHandle": [],
    # "Client": [],
    # "ClientResult": [],
    # "DeviceAuthorizationArgs": [],
    # "GuildChannel": [],
    # "GuildMinimal": [],
    # "LinkedChannel": [],
    # "LinkedLobby": [],
    # "LobbyHandle": [],
    # "LobbyMemberHandle": [],
    # "MessageHandle": [],
    # "RelationshipHandle": [],
    # "UserHandle": [],
    # "VADThresholdSettings": [],
    # "VoiceStateHandle": [],
}
