CLASSES = {
    "Activity": [
        "std::string 	Name () const",
        "void 	SetName (std::string Name)",
        "discordpp::ActivityTypes 	Type () const",
        "void 	SetType (discordpp::ActivityTypes Type)",
        "std::optional< std::string > 	State () const",
        "void 	SetState (std::optional< std::string > State)",
        "std::optional< std::string > 	Details () const",
        "void 	SetDetails (std::optional< std::string > Details)",
        "std::optional< uint64_t > 	ApplicationId () const",
        "void 	SetApplicationId (std::optional< uint64_t > ApplicationId)",
        "std::optional< discordpp::ActivityAssets > 	Assets () const",
        "void 	SetAssets (std::optional< discordpp::ActivityAssets > Assets)",
        "std::optional< discordpp::ActivityTimestamps > 	Timestamps () const",
        "void 	SetTimestamps (std::optional< discordpp::ActivityTimestamps > Timestamps)",
        "std::optional< discordpp::ActivityParty > 	Party () const",
        "void 	SetParty (std::optional< discordpp::ActivityParty > Party)",
        "std::optional< discordpp::ActivitySecrets > 	Secrets () const",
        "void 	SetSecrets (std::optional< discordpp::ActivitySecrets > Secrets)",
        "discordpp::ActivityGamePlatforms 	SupportedPlatforms () const",
        "void 	SetSupportedPlatforms (discordpp::ActivityGamePlatforms SupportedPlatforms)",
    ],
    # "ActivityAssets": [
    #     "std::optional< std::string > 	LargeImage () const",
    #     "void 	SetLargeImage (std::optional< std::string > LargeImage)",
    #     "std::optional< std::string > 	LargeText () const",
    #     "void 	SetLargeText (std::optional< std::string > LargeText)",
    #     "std::optional< std::string > 	SmallImage () const",
    #     "void 	SetSmallImage (std::optional< std::string > SmallImage)",
    #     "std::optional< std::string > 	SmallText () const",
    #     "void 	SetSmallText (std::optional< std::string > SmallText)",
    # ],
    # "ActivityInvite": [],
    # "ActivityParty": [],
    # "ActivitySecrets": [],
    # "ActivityTimestamps": [],
    # "AdditionalContent": [],
    # "AudioDevice": [],
    # "AuthorizationArgs": [],
    # "AuthorizationCodeChallenge": [],
    # "AuthorizationCodeVerifier": [],
    # "Call": [],
    # "CallInfoHandle": [],
    # "ChannelHandle": [],
    # "Client": [
    #     # Core
    #     "void 	AddLogCallback (discordpp::Client::LogCallback callback, discordpp::LoggingSeverity minSeverity)",
    # ],
    # "ClientResult": [
    #     "std::string 	ToString () const",
    #     "discordpp::ErrorType 	Type () const",
    #     "void 	SetType (discordpp::ErrorType Type)",
    #     "std::string 	Error () const",
    #     "void 	SetError (std::string Error)",
    #     "int32_t 	ErrorCode () const",
    #     "void 	SetErrorCode (int32_t ErrorCode)",
    #     "discordpp::HttpStatusCode 	Status () const",
    #     "void 	SetStatus (discordpp::HttpStatusCode Status)",
    #     "std::string 	ResponseBody () const",
    #     "void 	SetResponseBody (std::string ResponseBody)",
    #     "bool 	Successful () const",
    #     "void 	SetSuccessful (bool Successful)",
    #     "bool 	Retryable () const",
    #     "void 	SetRetryable (bool Retryable)",
    #     "float 	RetryAfter () const",
    #     "void 	SetRetryAfter (float RetryAfter)",
    # ],
    # "DeviceAuthorizationArgs": [],
    # "GuildChannel": [],
    # "GuildMinimal": [],
    # "LinkedChannel": [],
    # "LinkedLobby": [],
    # "LobbyHandle": [],
    # "LobbyMemberHandle": [],
    # "MessageHandle": [],
    # "RelationshipHandle": [],
    # "UserHandle": [],
    # "VADThresholdSettings": [],
    # "VoiceStateHandle": [],
}
