name: Build
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-linx-windows:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thiagola92/discord-social-sdk:latest
      env:
        # Discord downloader.
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}

        # Discord GDExtension.
        GODOT: /workspace/godot
    steps:
      # Execute the Discord downloader.
      - run: cd /workspace/discord-social-sdk-downloader && uv run main.py
      - run: echo "DISCORD_VERSION=$(cat /workspace/discord-social-sdk-downloader/version)" >> "$GITHUB_ENV"

      # Setup GDExtension repository.
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: mv /workspace/discord-social-sdk-downloader/DiscordSocialSdk*.zip .

      # Restore SCons cache.
      - uses: actions/cache/restore@v5
        with:
          path: .scons-cache/
          key: linux-windows-${{ env.DISCORD_VERSION }}-${{ github.ref }}
        continue-on-error: true

      # Unzip libraries and headers to correct directories.
      - run: unzip DiscordSocialSdk*.zip -d /tmp/
      - run: cp -r /tmp/discord_social_sdk/* sdk/
      - run: rm -rf /tmp/discord_social_sdk

      # Generate GDExtension API files.
      - run: cd godot-cpp && $GODOT --headless --dump-extension-api && scons custom_api_file=extension_api.json

      # Generate GDExtension source code.
      - run: python scripts/main.py --code

      # Generate GDExtension library.
      - run: scons custom_api_file=godot-cpp/extension_api.json

      # Open project, at least once, to be able to generate GDExtension documentation.
      - run: $GODOT --headless --quit ./demo/project.godot

      # Generate GDExtension documentations.
      - run: python scripts/main.py --docs

      # Link documentation to GDExtension library.
      - run: scons custom_api_file=godot-cpp/extension_api.json

      # Build for many platforms.
      - run: scons platform=linux    target=template_debug   arch=x86_64 custom_api_file=godot-cpp/extension_api.json
      - run: scons platform=linux    target=template_release arch=x86_64 custom_api_file=godot-cpp/extension_api.json
      - run: scons platform=windows  target=template_debug   arch=x86_64 custom_api_file=godot-cpp/extension_api.json
      - run: scons platform=windows  target=template_release arch=x86_64 custom_api_file=godot-cpp/extension_api.json

      # Generate new ZIP file.
      - run: zip -r discord_social_sdk.zip demo/addons/discord_social_sdk/**

      # Upload ZIP file.
      - uses: actions/upload-artifact@v7
        with:
          path: discord_social_sdk.zip
          archive: false

      # Save SCons cache.
      - uses: actions/cache/save@v5
        with:
          path: .scons-cache/
          key: linux-windows-${{ env.DISCORD_VERSION }}-${{ github.ref }}
        continue-on-error: true

      # Update GDExtension repository
      - run: git config --global user.name 'GitHub Action'
      - run: git config --global user.email 'action@github.com'
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: git add -A
      - run: git commit -m "Build artifacts"
      - run: git push
